## Data Encoding
1. Nominal
2. Label and Ordinal
3. Target Guided Ordinal Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
# create simple dataframe
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [ ]:
# create an instance of OHE
encoder=OneHotEncoder()

In [5]:
#perform fit and transfoem
encoded=encoder.fit_transform(df[['color']]).toarray()

In [6]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [7]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [8]:
encoder.transform([['blue']]).toarray()

C:\Users\91620\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [9]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

## Label Encoding

In [11]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [12]:
lbl_encoder.fit_transform(df[['color']])

C:\Users\91620\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [13]:
lbl_encoder.transform([['red']])

C:\Users\91620\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [ ]:
## ordinal encoding : assign rank

In [14]:
from sklearn.preprocessing import OrdinalEncoder

In [15]:
df = pd.DataFrame({
    'size':['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [16]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [17]:
## create instance of ordinal encoder then fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [18]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [19]:
encoder.transform([['small']])

C:\Users\91620\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])