In [1]:
import pandas as pd

#create sample dataframe with categorical variable and a target variable

df=pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [100,150,300,250,180,320]
})

In [2]:
df

       city  price
0  New York    100
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [3]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [4]:
mean_price

{'London': 150.0, 'New York': 140.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [5]:
df['city_encoded'] = df['city'].map(mean_price)

In [6]:
df[['price','city_encoded']]

   price  city_encoded
0    100         140.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         140.0
5    320         310.0