In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data.csv')
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [8]:
# Handling Missing values
df.isnull().any()
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [11]:
df_filled = df.fillna(0)
df_filled.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       0
Region      0
dtype: int64

In [19]:
# Missing value with mean of column
df['sales_fill'] = df['Sales'].fillna(df['Sales'].mean())
df['sales_fill'].isnull().any()
df.head(3)

         Date Category  Value   Product  Sales Region  sales_fill
0  2023-01-01        A   28.0  Product1  754.0   East       754.0
1  2023-01-02        B   39.0  Product3  110.0  North       110.0
2  2023-01-03        C   32.0  Product2  398.0   East       398.0

In [22]:
# renaming column
df = df.rename(columns={'Date':'Sales_date'})
df.head(2)

   Sales_date Category  Value   Product  Sales Region  sales_fill
0  2023-01-01        A   28.0  Product1  754.0   East       754.0
1  2023-01-02        B   39.0  Product3  110.0  North       110.0

In [12]:
#Change data type
df['Value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head(3)

         Date Category  Value   Product  Sales Region  New_value  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East    21952.0         28
1  2023-01-02        B   39.0  Product3  110.0  North    59319.0         39
2  2023-01-03        C   32.0  Product2  398.0   East    32768.0         32

In [15]:
df['New_value'] = df['Value'].apply(lambda x:x**3)
df.head(3)

         Date Category  Value   Product  Sales Region  New_value  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East    21952.0         28
1  2023-01-02        B   39.0  Product3  110.0  North    59319.0         39
2  2023-01-03        C   32.0  Product2  398.0   East    32768.0         32

In [17]:
# Data aggregating and grouping

df.head()
grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [19]:
grouped_sum = df.groupby(['Product','Region'])['Value'].sum()
grouped_sum

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [21]:
## aggregate multiple function
group_agg = df.groupby('Region')['Value'].agg(['mean','sum','count'])
group_agg

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [4]:
### Merging and joining Dataframes
# Create sample DataFrames
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [23]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [6]:
##Merging dataframe
pd.merge(df1, df2, on="Key",how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [7]:
pd.merge(df1, df2, on="Key",how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [8]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [9]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6